# Generated by Django 2.2.1 on 2019-05-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default.png', upload_to='projects_pics'),
        ),
    ]
